# .github/FUNDING.yml
# =========================================
# Project: github-doc-cookiecutter
# =========================================
# These are supported funding model platforms
---

# github: [jcook3701]
buy_me_a_coffee: jcook3701
