---
# Enable all built-in rules by default
default: true

# MD007/ul-indent: Set unordered list indentation to 2 spaces
MD007:
  indent: 2

# MD013/line-length: Disable or adjust long line warnings
# Many developers disable this to allow long URLs or technical prose
MD013: false

# MD022/blanks-around-headings: Headings should be surrounded by blank lines
# Disabling this allows headings to be immediately preceded or followed by text
MD022: false

# MD024/no-duplicate-heading: Allow duplicate headings if they are not siblings
MD024:
  siblings_only: true

# MD029/ol-prefix: Use 1. 2. 3. for ordered lists (default is "one" i.e., 1. 1. 1.)
MD029:
  style: "ordered"

# MD032/blanks-around-lists: Lists should be surrounded by blank lines
# Setting this to false ignores the rule entirely
MD032: false

# MD033/no-inline-html: Allow specific HTML tags if needed
MD033:
  allowed_elements: ["br", "details", "summary"]

# MD041/first-line-h1: Ensure the file starts with a top-level heading
MD041: true

# MD046/code-block-style: Enforce fenced code blocks (```)
MD046:
  style: "fenced"
